### ISSUE TITLE
makeslice: len out of range

### ISSUE THREAD

**Issue by rikumi** [yoki123/ncmdump#7]
```plain
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
main.processFile(0x7ffeefbfe858, 0x1b)
        D:/Projects/ncmdump/src/ncmdump/main.go:144 +0x462
main.main()
        D:/Projects/ncmdump/src/ncmdump/main.go:282 +0x6b6
```

**Comment by rikumi** [comment]
处理 flac 的 ncm 文件，报这个错

**Comment by yoki123** [comment]
能提供源文件么

**Comment by shinvdu** [comment]
我也遇到了这个问题，留个邮箱，下周给你发源文件

**Comment by yoki123** [comment]
@shinvdu  主页上的邮件就可以

**Comment by mingcheng** [comment]
#9 这块已经修复，新版拿不到 meta 的 length，所以需要单独判断

**Comment by mingcheng** [comment]
https://github.com/mingcheng/ncmdump.go/blob/master/ncmdump.go#L148

**Comment by shinvdu** [comment]
大赞一个!

**Comment by yoki123** [comment]
#9
